"""add created_at default to messages

Revision ID: d2659bbfa47a
Revises: 4863137c56a0
Create Date: 2026-08-18 00:36:27.860589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2659bbfa47a'
down_revision: Union[str, Sequence[str], None] = '4863137c56a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade():
    message_role = sa.Enum(
        'USER',
        'ASSISTANT',
        name='messagerole'
    )

    message_role.create(
        op.get_bind(),
        checkfirst=True
    )

    op.alter_column(
        'messages',
        'role',
        existing_type=sa.VARCHAR(length=20),
        type_=message_role,
        existing_nullable=False,
        postgresql_using="role::messagerole"
    )

    op.alter_column(
        'messages',
        'created_at',
        existing_type=sa.DateTime(timezone=True),
        server_default=sa.text('now()'),
        existing_nullable=False
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.alter_column('messages', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('messages', 'role',
               existing_type=sa.Enum('USER', 'ASSISTANT', name='messagerole'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('messages', 'content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.alter_column('conversations', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('conversations', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('conversations', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
